apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicustomer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apicustomer
  template:
    metadata:
      labels:
        app: apicustomer
    spec:
      containers:
        - name: apicustomer
          image: bagrt/starly-customer:latest
          ports:
            - containerPort: 80