apiVersion: v1
kind: Service
metadata:
  name: apicustomer-loadbalancer
spec:
  selector:
    app: apicustomer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31840
  type: LoadBalancer